### ISSUE TITLE
generator yo nodeserver is broken

### ISSUE THREAD

**Issue by tobespc** [ibm-developer/generator-ibm-web#59]
Looks like the update yesterday has broken https://github.com/ibm-developer/generator-nodeserver

We get the following trying to run any node generation

Error: Cannot find module '../../lib/handlebars.js'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-nodeserver/node_modules/generator-ibm-web/generators/app/index.js:19:20)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.get [as ibm-web:app] (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:39:27)
    at Store.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:62:39)
    at Environment.get (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:342:23)
    at Environment.getByPath (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:359:19)

    at ChildProcess.exithandler (child_process.js:276:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  killed: false,
  code: 1,
  signal: null,

**Comment by rnchamberlain** [comment]
I think that the problem may be that the /lib directory (where generators/app/index.js is expecting to find handlebars.js) not included in the npm package:
```
C:\test\node_modules\generator-ibm-web>ls -la
total 33
drwxrwxrwx   1 user     group           0 Nov 15 11:30 .
drwxrwxrwx   1 user     group           0 Nov 15 11:31 ..
-rw-rw-rw-   1 user     group       11843 Nov 15 11:30 CHANGELOG.md
-rw-rw-rw-   1 user     group       11357 Nov 15 11:30 LICENSE
-rw-rw-rw-   1 user     group        4218 Nov 15 11:30 README.md
drwxrwxrwx   1 user     group           0 Nov 15 11:30 generators
drwxrwxrwx   1 user     group           0 Nov 15 11:30 node_modules
-rw-rw-rw-   1 user     group        4055 Nov 15 11:30 package.json
```

**Comment by ebullient** [comment]
The issue is in package.json, it needs to include the lib dir with the files.
